version: "3.8"

services:
  # traefik:
  #   image: "traefik:v2.10"
  #   command:
  #     - "--api.insecure=true"
  #     - "--log.level=DEBUG"
  #     - "--providers.docker=true"
  #     - "--entrypoints.web.address=:19080"
  #   ports:
  #     - "19080:19080"
  #     - "19081:8080" # for the dashboard
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #   environment:
  #     - ACME_EMAIL=brunogabrielpk@gmail.com

  app:
    build: .
    #labels:
    # - "traefik.enable=true"
    # #- "traefik.http.routers.app.rule=Host(`168.181.149.171`, `localhost`)"
    # - "traefik.http.routers.app.rule=PathPrefix(`/app`)"
    # - "traefik.http.routers.app.entrypoints=web"
    # - "traefik.http.services.app.loadbalancer.server.port=19080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=pdfconverter
    depends_on:
      - db
    ports:
      - "0.0.0.0:19080:19080"

  # whoami:
  #   image: "traefik/whoami"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
  #     - "traefik.http.routers.whoami.entrypoints=web"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pdfconverter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
