version: "3.8"

services:
  traefik:
    image: "traefik:v2.10"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:40110"
      #- "--entrypoints.websecure.address=:9443"
    ports:
      - "40110:40110"
      - "9443:9443"
      - "19081:8080" # for the dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./acme.json:/acme.json"
    environment:
      - ACME_EMAIL=brunogabrielpk@gmail.com

  app:
    build: .
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.app.rule=Host(`pdf.localhost`) || HOST(`localhost`)"
      - "traefik.http.routers.app.rule=Host(`168.181.149.171` || `pdf.localhost`) || HOST(`localhost`))"
      #- "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.entrypoints=web"
      #- "traefik.http.routers.app.tls.certresolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=40110"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=pdfconverter
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pdfconverter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
