entryPoints:
  web:
    address: ":19080"
  websecure:
    address: ":9443"

providers:
  docker:
    exposedByDefault: false

#certificatesResolvers:
#letsencrypt:
#acme:
#email: "${ACME_EMAIL}"
#storage: "acme.json"
#httpChallenge:
#entryPoint: web
